# Generated by Django 3.1.5 on 2021-09-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('general', 'General'), ('giveaway', 'Giveaway'), ('entertainment', 'Entertainment'), ('telecommunication', 'Telecommunication'), ('medical', 'Medical'), ('religion', 'Religion'), ('fitness', 'Fitness'), ('gossip', 'Gossip'), ('computer science', 'Computer Science'), ('business', 'Business'), ('fitness', 'Fitness'), ('marriage', 'Marriage'), ('movie', 'Movie'), ('health', 'Health'), ('books', 'Books and Novels'), ('fashion', ' Fashion and Beauty'), ('skin-care', 'Skin Care'), ('politics', 'Politics'), ('engineering', 'Engineering'), ('food', 'Foods and Nutrition'), ('graphics', 'Grpahics design'), ('fashion', 'Fashion'), ('media', 'Media'), ('tricks_and_hacks', 'Tricks and Hacks'), ('psychology', 'Psychology'), ('sports', 'Sports'), ('food', 'Foods'), ('technology', 'Technology'), ('religion', 'Religion'), ('others', 'Others')], default='general', max_length=200),
        ),
    ]
