# Generated by Django 3.1.5 on 2021-05-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='jamb_subject',
            new_name='jamb_subjects',
        ),
    ]
