# Generated by Django 3.1.5 on 2021-07-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210507_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='no_of_views',
            field=models.IntegerField(default='100'),
        ),
    ]
